name: Test and release
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        redis-version: [6, 7]
        mongodb-version: [5.0, 6.0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Start Redis ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm exec nx affected --target=build --all --parallel
      - name: Lint
        run: pnpm exec nx affected --target=lint --all --parallel
      - name: Test
        run: pnpm exec nx affected --target=test --all --parallel --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
  publishing:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm exec nx affected --target=build --all --parallel
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
